on: [push]

jobs:
  do_while_not_queued:
    runs-on: ubuntu-latest
    name: do-while-not-queued
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: do-while-not-queued step
        uses: ./ # Uses an action in the root directory
        with:
          commandLine: 'pwsh'
          args: '-command;Start-Sleep -Seconds 2'
          workflow: ${{ github.WORKFLOW }}
          maxRuns: 7
          maxTimeSec: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}